---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-labs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubevirt
  namespace: kubevirt-labs
spec:
   interval: 12h0m
   url: https://github.com/kubevirt/kubevirt.git
   ref:
     branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: kubevirt-labs
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubevirt
  path: releases/download/v1.4.0/kubevirt-operator.yaml