apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - kubevirt.yaml
patches:
  - path: delete-metallb-ns.yaml
  - path: delete-metallb-helmrepo.yaml
  - path: delete-metallb-hr.yaml