---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 1h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name:  minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: "5.x.x" # Pin to a specific major/minor version
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Values to pass to the cert-manager Helm chart
  # See https://cert-manager.io/docs/installation/helm/#configuration
  values:
    installCRDs: true # Automatically install CRDs. Essential for cert-manager to work.