---
apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-labs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kamaji
  namespace: kamaji-labs
spec:
  interval: 5m0s
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-labs
spec:
  interval: 60m
  chart:
    spec:
      chart: kamaji
      version: "0.x"
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: kamaji
  test:
    enable: true
