---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-labs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-labs
spec:
  interval: 5m0s
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-labs
spec:
  interval: 60m
  chart:
    spec:
      chart: metallb
      version: "0.x"
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: metallb
  test:
    enable: true
